apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akeneo.fullname" . }}-deployment
  labels:
    {{- include "akeneo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.akeneo.replicas }}
  selector:
    matchLabels:
      {{- include "akeneo.selectorLabels" . | nindent 6 }}
      role: web
  template:
    metadata:
      labels:
        {{- include "akeneo.selectorLabels" . | nindent 8 }}
        role: web
    spec:
      {{- with .Values.akeneo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.akeneo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.akeneo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: php
        resources:
          {{- toYaml .Values.akeneo.resources | nindent 12 }}
        image: {{ include "akeneo.image" . }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        envFrom:
          - configMapRef:
              name:  {{ include "akeneo.fullname" . }}-configmap
          - secretRef:
              name:  {{ include "akeneo.fullname" . }}-secret
        ports:
        - containerPort: {{ .Values.akeneo.service.port }}
          name: http
        livenessProbe:
          {{- toYaml .Values.akeneo.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.akeneo.readinessProbe | nindent 12 }}
        volumeMounts:
          - mountPath: /app/config/packages/prod/oneup_flysystem.yml
            name: config-files
            subPath: oneup_flysystem.yml
      volumes:
        - name: config-files
          configMap:
            name: {{ include "akeneo.fullname" . }}-files-configmap
