{{- if not .Values.mysql.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akeneo.fullname" . }}-mysql-service
  labels:
  {{- include "akeneo.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "akeneo.selectorLabels" . | nindent 4 }}
    role: mysql
  ports:
    - name: mysql
      port: 3306
{{- end }}
