{{- if and (not .Values.config.existingSecret) (.Values.config.rawYaml) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apprise.fullname" . }}-secret
  labels:
    {{- include "apprise.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.config.rawYaml }}
  {{ $key }}: {{ $val | b64enc }} 
  {{- end }}
{{- end}}