apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "mongodb-backups" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    name: {{ default "mongodb-backups" .Release.Name }}
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }} 
