apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    name: {{ default "mongodb-backups" .Release.Name }}
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ default "mongodb-backups" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
